name: "Déploiement CI/CD vers itch.io"

on:
  push:
    branches:
      - main # Le déploiement s'active uniquement quand on merge sur main

jobs:
  export-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: ⚙️ Exportation du jeu Godot (WebAssembly)
        uses: firebelley/godot-export@v5
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Déploiement sur itch.io via Butler
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: you-ai
          ITCH_USER: brasseva
          PACKAGE: build/Web/Web.zip